# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo.xci
# IP: The module: 'rng_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo/rng_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo/rng_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo.xci
# IP: The module: 'rng_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo/rng_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo/rng_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
