# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.cache/wt [current_project]
set_property parent.project_path /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
add_files -quiet /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rchip_axi4_xbar/rchip_axi4_xbar.dcp
set_property used_in_implementation false [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rchip_axi4_xbar/rchip_axi4_xbar.dcp]
add_files -quiet /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/read_metadata_fifo/read_metadata_fifo.dcp
set_property used_in_implementation false [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/read_metadata_fifo/read_metadata_fifo.dcp]
add_files -quiet /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo.dcp
set_property used_in_implementation false [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rng_fifo/rng_fifo.dcp]
add_files -quiet /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/wrdata_fifo/wrdata_fifo.dcp
set_property used_in_implementation false [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/wrdata_fifo/wrdata_fifo.dcp]
add_files -quiet /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/wrmask_fifo/wrmask_fifo.dcp
set_property used_in_implementation false [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/wrmask_fifo/wrmask_fifo.dcp]
read_verilog {
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/util.vh
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/encoding.vh
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/parameters.vh
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/rocket-chip/clocking.vh
}
add_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/system.bd]

read_verilog -library xil_defaultlib -sv {
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/timing_counter.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/scheduler.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/command_timer.sv
}
read_verilog -library xil_defaultlib {
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_if_post_fifo.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_byte_group_io.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_poc_tap_base.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_poc_meta.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_poc_edge_store.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_poc_cc.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_byte_lane.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_poc_top.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_4lanes.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_poc_pd.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_prbs_gen.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_wrcal.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_tempmon.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_init.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_mc_phy.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/violated_timing_counter.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_calib_top.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scd_phy_conv.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/perops_controller.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_tempmon.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_iodelay_ctrl.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_infrastructure.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_ddr_phy_top.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/mig_7series_v4_0_clk_ibuf.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/imo_controller.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/cr_file.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/axi_to_mc.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/rocket-chip/plusarg_reader.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/phy/memctl_mig.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/top/controller_top.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/rocket-chip/AsyncResetReg.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/rocket-chip/Top.ZynqCopyFPGAConfig.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/top/memctl_sys_top.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/system_top.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/poc_ctrlr.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/top/poc_design.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/sim/tb_axi_to_mc.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/rlrd_scheduler.v
  /home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/hdl/impl/controller/scheduler/apa_scheduler.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/constrs_1/new/fullsystem_ZC706.xdc
set_property used_in_implementation false [get_files /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/constrs_1/new/fullsystem_ZC706.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_top -part xc7z045ffg900-2


write_checkpoint -force -noxdef system_top.dcp

catch { report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb }
