set_property SRC_FILE_INFO {cfile:/home/ataberk/EasyDRAM/controller-hardware/ZC706/sources/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc rfile:../../../../sources/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:zynq_ps/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/constrs_1/new/fullsystem_ZC706.xdc rfile:../../../E2E_RowClone.srcs/constrs_1/new/fullsystem_ZC706.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D19" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D18" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C19" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H18" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E20" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E18" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D20" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J18" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B20" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A20" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B21" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H17" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G21" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K18" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G22" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K17" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H21" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L18" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H22" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L17" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G20" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M17" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G19" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M19" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J21" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L20" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J19" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M20" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J20" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K20" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K21" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C22" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B22" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F22" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E21" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A23" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E22" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A24" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C21" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D24" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C24" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E23" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C23" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F23" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D23" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F24" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M21" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N21" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N23" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N24" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L23" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F25" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L28" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G29" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C29" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C26" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L29" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F29" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B29" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B26" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A27" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A29" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E27" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D26" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E26" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B25" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D25" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M30" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L30" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B27" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M29" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K30" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J28" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J30" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K27" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J29" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F30" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G30" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F28" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E30" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E25" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E28" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H28" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G27" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H27" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D29" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D28" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D30" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C28" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A28" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A30" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A25" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K28" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H29" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B30" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C27" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N22" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M22" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K25" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J25" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M24" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M25" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M26" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M27" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J23" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F27" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K22" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H26" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G24" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J26" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G25" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L27" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K26" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J24" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H23" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K23" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H24" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G26" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L25" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D21" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B19" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A22" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports sys_rst]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports init_calib_complete]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3 [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G5 [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E5 [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10 [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L9 [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J9 [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K11 [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:2 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L10 [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10 [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:2 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:2 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:2 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:2 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:2 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:2 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:2 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:2 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:2 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:2 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:2 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J8 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:2 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:2 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E8 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:2 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F9 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:2 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:2 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:2 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:2 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:2 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:2 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:2 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:2 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:2 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:2 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports ddr3_ras_n]
set_property src_info {type:XDC file:2 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E7 [get_ports ddr3_cas_n]
set_property src_info {type:XDC file:2 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports ddr3_we_n]
set_property src_info {type:XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports ddr3_reset_n]
set_property src_info {type:XDC file:2 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:2 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:2 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:2 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:2 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:2 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:2 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:2 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:2 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:2 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11 [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:2 line:630 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports sys_clk_p]
set_property src_info {type:XDC file:2 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports sys_clk_n]
set_property src_info {type:XDC file:2 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:2 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:2 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:2 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:2 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:2 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:2 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:2 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:2 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:2 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:2 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:2 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:2 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:2 line:708 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:2 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:2 line:719 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:2 line:729 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports ddr3_ck_p]
set_property src_info {type:XDC file:2 line:730 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports ddr3_ck_n]
set_property src_info {type:XDC file:2 line:800 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y19 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:2 line:801 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y18 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:2 line:802 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y17 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:2 line:803 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y16 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:2 line:804 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y23 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:2 line:805 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y22 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:2 line:806 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y21 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:2 line:807 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y20 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:2 line:808 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y26 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:2 line:809 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y25 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:2 line:810 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y24 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:2 line:812 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y19 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:813 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y18 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:814 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y17 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:815 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y16 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:819 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y20 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:820 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y26 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:821 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y25 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y24 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:2 line:826 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y19 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:2 line:827 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y18 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:2 line:828 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y17 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:2 line:829 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y16 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:2 line:830 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y23 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:2 line:831 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y22 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:2 line:832 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y21 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:2 line:833 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y20 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:2 line:834 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y26 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:2 line:835 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y25 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:2 line:836 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y24 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:2 line:838 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y19 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:839 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y18 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:840 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y17 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:841 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y16 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:842 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y20 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:843 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y26 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:844 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y25 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:845 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y24 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:2 line:847 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:2 line:848 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y5 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:2 line:849 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y6 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:2 line:851 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y4 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:2 line:852 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y5 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:2 line:853 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y6 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:2 line:855 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y243 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:856 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y231 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:857 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y219 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:858 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y207 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:859 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y257 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:860 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y331 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:861 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y319 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:862 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y307 [get_cells -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:2 line:865 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y5 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:XDC file:2 line:866 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y5 [get_cells -hier -filter {NAME =~ */u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
set_property src_info {type:XDC file:2 line:885 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20.000
set_property src_info {type:XDC file:2 line:886 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] 5.000
set_property src_info {type:XDC file:2 line:890 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20.000
set_property src_info {type:XDC file:2 line:897 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {memctl/mem_ctl_top/crf/rng_prd[0]} {memctl/mem_ctl_top/crf/rng_prd[1]} {memctl/mem_ctl_top/crf/rng_prd[2]} {memctl/mem_ctl_top/crf/rng_prd[3]} {memctl/mem_ctl_top/crf/rng_prd[4]} {memctl/mem_ctl_top/crf/rng_prd[5]} {memctl/mem_ctl_top/crf/rng_prd[6]} {memctl/mem_ctl_top/crf/rng_prd[7]} {memctl/mem_ctl_top/crf/rng_prd[8]} {memctl/mem_ctl_top/crf/rng_prd[9]} {memctl/mem_ctl_top/crf/rng_prd[10]} {memctl/mem_ctl_top/crf/rng_prd[11]} {memctl/mem_ctl_top/crf/rng_prd[12]} {memctl/mem_ctl_top/crf/rng_prd[13]} {memctl/mem_ctl_top/crf/rng_prd[14]} {memctl/mem_ctl_top/crf/rng_prd[15]} {memctl/mem_ctl_top/crf/rng_prd[16]} {memctl/mem_ctl_top/crf/rng_prd[17]} {memctl/mem_ctl_top/crf/rng_prd[18]} {memctl/mem_ctl_top/crf/rng_prd[19]} {memctl/mem_ctl_top/crf/rng_prd[20]} {memctl/mem_ctl_top/crf/rng_prd[21]} {memctl/mem_ctl_top/crf/rng_prd[22]} {memctl/mem_ctl_top/crf/rng_prd[23]} {memctl/mem_ctl_top/crf/rng_prd[24]} {memctl/mem_ctl_top/crf/rng_prd[25]} {memctl/mem_ctl_top/crf/rng_prd[26]} {memctl/mem_ctl_top/crf/rng_prd[27]} {memctl/mem_ctl_top/crf/rng_prd[28]} {memctl/mem_ctl_top/crf/rng_prd[29]} {memctl/mem_ctl_top/crf/rng_prd[30]} {memctl/mem_ctl_top/crf/rng_prd[31]}]]
set_property src_info {type:XDC file:2 line:898 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list memctl/mem_ctl_top/crf/rng_boost_enable]]
set_property src_info {type:XDC file:2 line:901 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:902 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:903 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:904 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:905 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:906 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:907 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:908 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:909 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:910 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:911 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list memctl/phy/u_ddr3_infrastructure/poc_sample_pd_r_reg_0]]
set_property src_info {type:XDC file:2 line:912 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:913 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:914 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {memctl/imoControllerIO_imo_out_inst[0]} {memctl/imoControllerIO_imo_out_inst[1]} {memctl/imoControllerIO_imo_out_inst[2]} {memctl/imoControllerIO_imo_out_inst[3]} {memctl/imoControllerIO_imo_out_inst[4]} {memctl/imoControllerIO_imo_out_inst[5]} {memctl/imoControllerIO_imo_out_inst[6]} {memctl/imoControllerIO_imo_out_inst[7]} {memctl/imoControllerIO_imo_out_inst[8]} {memctl/imoControllerIO_imo_out_inst[9]} {memctl/imoControllerIO_imo_out_inst[10]} {memctl/imoControllerIO_imo_out_inst[11]} {memctl/imoControllerIO_imo_out_inst[12]} {memctl/imoControllerIO_imo_out_inst[13]} {memctl/imoControllerIO_imo_out_inst[14]} {memctl/imoControllerIO_imo_out_inst[15]} {memctl/imoControllerIO_imo_out_inst[16]} {memctl/imoControllerIO_imo_out_inst[17]} {memctl/imoControllerIO_imo_out_inst[18]} {memctl/imoControllerIO_imo_out_inst[19]} {memctl/imoControllerIO_imo_out_inst[20]} {memctl/imoControllerIO_imo_out_inst[21]} {memctl/imoControllerIO_imo_out_inst[22]} {memctl/imoControllerIO_imo_out_inst[23]} {memctl/imoControllerIO_imo_out_inst[24]} {memctl/imoControllerIO_imo_out_inst[25]} {memctl/imoControllerIO_imo_out_inst[26]} {memctl/imoControllerIO_imo_out_inst[27]} {memctl/imoControllerIO_imo_out_inst[28]} {memctl/imoControllerIO_imo_out_inst[29]} {memctl/imoControllerIO_imo_out_inst[30]} {memctl/imoControllerIO_imo_out_inst[31]} {memctl/imoControllerIO_imo_out_inst[32]} {memctl/imoControllerIO_imo_out_inst[33]} {memctl/imoControllerIO_imo_out_inst[34]} {memctl/imoControllerIO_imo_out_inst[35]} {memctl/imoControllerIO_imo_out_inst[36]} {memctl/imoControllerIO_imo_out_inst[37]} {memctl/imoControllerIO_imo_out_inst[38]} {memctl/imoControllerIO_imo_out_inst[39]} {memctl/imoControllerIO_imo_out_inst[40]} {memctl/imoControllerIO_imo_out_inst[41]} {memctl/imoControllerIO_imo_out_inst[42]} {memctl/imoControllerIO_imo_out_inst[43]} {memctl/imoControllerIO_imo_out_inst[44]} {memctl/imoControllerIO_imo_out_inst[45]} {memctl/imoControllerIO_imo_out_inst[46]} {memctl/imoControllerIO_imo_out_inst[47]} {memctl/imoControllerIO_imo_out_inst[48]} {memctl/imoControllerIO_imo_out_inst[49]} {memctl/imoControllerIO_imo_out_inst[50]} {memctl/imoControllerIO_imo_out_inst[51]} {memctl/imoControllerIO_imo_out_inst[52]} {memctl/imoControllerIO_imo_out_inst[53]} {memctl/imoControllerIO_imo_out_inst[54]} {memctl/imoControllerIO_imo_out_inst[55]} {memctl/imoControllerIO_imo_out_inst[56]} {memctl/imoControllerIO_imo_out_inst[57]} {memctl/imoControllerIO_imo_out_inst[58]} {memctl/imoControllerIO_imo_out_inst[59]} {memctl/imoControllerIO_imo_out_inst[60]} {memctl/imoControllerIO_imo_out_inst[61]} {memctl/imoControllerIO_imo_out_inst[62]} {memctl/imoControllerIO_imo_out_inst[63]} {memctl/imoControllerIO_imo_out_inst[64]} {memctl/imoControllerIO_imo_out_inst[65]} {memctl/imoControllerIO_imo_out_inst[66]} {memctl/imoControllerIO_imo_out_inst[67]} {memctl/imoControllerIO_imo_out_inst[68]} {memctl/imoControllerIO_imo_out_inst[69]} {memctl/imoControllerIO_imo_out_inst[70]} {memctl/imoControllerIO_imo_out_inst[71]} {memctl/imoControllerIO_imo_out_inst[72]} {memctl/imoControllerIO_imo_out_inst[73]} {memctl/imoControllerIO_imo_out_inst[74]} {memctl/imoControllerIO_imo_out_inst[75]} {memctl/imoControllerIO_imo_out_inst[76]} {memctl/imoControllerIO_imo_out_inst[77]} {memctl/imoControllerIO_imo_out_inst[78]} {memctl/imoControllerIO_imo_out_inst[79]} {memctl/imoControllerIO_imo_out_inst[80]} {memctl/imoControllerIO_imo_out_inst[81]} {memctl/imoControllerIO_imo_out_inst[82]} {memctl/imoControllerIO_imo_out_inst[83]} {memctl/imoControllerIO_imo_out_inst[84]} {memctl/imoControllerIO_imo_out_inst[85]} {memctl/imoControllerIO_imo_out_inst[86]} {memctl/imoControllerIO_imo_out_inst[87]} {memctl/imoControllerIO_imo_out_inst[88]} {memctl/imoControllerIO_imo_out_inst[89]} {memctl/imoControllerIO_imo_out_inst[90]} {memctl/imoControllerIO_imo_out_inst[91]} {memctl/imoControllerIO_imo_out_inst[92]} {memctl/imoControllerIO_imo_out_inst[93]} {memctl/imoControllerIO_imo_out_inst[94]} {memctl/imoControllerIO_imo_out_inst[95]} {memctl/imoControllerIO_imo_out_inst[96]} {memctl/imoControllerIO_imo_out_inst[97]} {memctl/imoControllerIO_imo_out_inst[98]} {memctl/imoControllerIO_imo_out_inst[99]} {memctl/imoControllerIO_imo_out_inst[100]} {memctl/imoControllerIO_imo_out_inst[101]} {memctl/imoControllerIO_imo_out_inst[102]} {memctl/imoControllerIO_imo_out_inst[103]} {memctl/imoControllerIO_imo_out_inst[104]} {memctl/imoControllerIO_imo_out_inst[105]} {memctl/imoControllerIO_imo_out_inst[106]} {memctl/imoControllerIO_imo_out_inst[107]} {memctl/imoControllerIO_imo_out_inst[108]} {memctl/imoControllerIO_imo_out_inst[109]} {memctl/imoControllerIO_imo_out_inst[110]} {memctl/imoControllerIO_imo_out_inst[111]} {memctl/imoControllerIO_imo_out_inst[112]} {memctl/imoControllerIO_imo_out_inst[113]} {memctl/imoControllerIO_imo_out_inst[114]} {memctl/imoControllerIO_imo_out_inst[115]} {memctl/imoControllerIO_imo_out_inst[116]} {memctl/imoControllerIO_imo_out_inst[117]} {memctl/imoControllerIO_imo_out_inst[118]} {memctl/imoControllerIO_imo_out_inst[119]} {memctl/imoControllerIO_imo_out_inst[120]} {memctl/imoControllerIO_imo_out_inst[121]} {memctl/imoControllerIO_imo_out_inst[122]} {memctl/imoControllerIO_imo_out_inst[123]} {memctl/imoControllerIO_imo_out_inst[124]} {memctl/imoControllerIO_imo_out_inst[125]} {memctl/imoControllerIO_imo_out_inst[126]} {memctl/imoControllerIO_imo_out_inst[127]}]]
set_property src_info {type:XDC file:2 line:915 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:916 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:917 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:918 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {memctl/mem_ctl_top/crf/cr_wdata[0]} {memctl/mem_ctl_top/crf/cr_wdata[1]} {memctl/mem_ctl_top/crf/cr_wdata[2]} {memctl/mem_ctl_top/crf/cr_wdata[3]} {memctl/mem_ctl_top/crf/cr_wdata[4]} {memctl/mem_ctl_top/crf/cr_wdata[5]} {memctl/mem_ctl_top/crf/cr_wdata[6]} {memctl/mem_ctl_top/crf/cr_wdata[7]} {memctl/mem_ctl_top/crf/cr_wdata[8]} {memctl/mem_ctl_top/crf/cr_wdata[9]} {memctl/mem_ctl_top/crf/cr_wdata[10]} {memctl/mem_ctl_top/crf/cr_wdata[11]} {memctl/mem_ctl_top/crf/cr_wdata[12]} {memctl/mem_ctl_top/crf/cr_wdata[13]} {memctl/mem_ctl_top/crf/cr_wdata[14]} {memctl/mem_ctl_top/crf/cr_wdata[15]} {memctl/mem_ctl_top/crf/cr_wdata[16]} {memctl/mem_ctl_top/crf/cr_wdata[17]} {memctl/mem_ctl_top/crf/cr_wdata[18]} {memctl/mem_ctl_top/crf/cr_wdata[19]} {memctl/mem_ctl_top/crf/cr_wdata[20]} {memctl/mem_ctl_top/crf/cr_wdata[21]} {memctl/mem_ctl_top/crf/cr_wdata[22]} {memctl/mem_ctl_top/crf/cr_wdata[23]} {memctl/mem_ctl_top/crf/cr_wdata[24]} {memctl/mem_ctl_top/crf/cr_wdata[25]} {memctl/mem_ctl_top/crf/cr_wdata[26]} {memctl/mem_ctl_top/crf/cr_wdata[27]} {memctl/mem_ctl_top/crf/cr_wdata[28]} {memctl/mem_ctl_top/crf/cr_wdata[29]} {memctl/mem_ctl_top/crf/cr_wdata[30]} {memctl/mem_ctl_top/crf/cr_wdata[31]}]]
set_property src_info {type:XDC file:2 line:919 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:920 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:921 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:922 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[9]_12[0]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[1]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[2]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[3]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[4]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[5]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[6]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[7]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[8]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[9]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[10]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[11]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[12]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[13]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[14]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[15]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[16]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[17]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[18]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[19]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[20]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[21]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[22]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[23]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[24]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[25]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[26]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[27]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[28]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[29]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[30]} {memctl/mem_ctl_top/crf/cr_rf[9]_12[31]}]]
set_property src_info {type:XDC file:2 line:923 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:924 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:925 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:926 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[8]_13[0]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[1]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[2]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[3]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[4]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[5]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[6]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[7]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[8]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[9]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[10]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[11]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[12]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[13]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[14]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[15]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[16]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[17]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[18]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[19]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[20]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[21]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[22]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[23]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[24]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[25]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[26]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[27]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[28]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[29]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[30]} {memctl/mem_ctl_top/crf/cr_rf[8]_13[31]}]]
set_property src_info {type:XDC file:2 line:927 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:928 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:929 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:930 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[7]_14[0]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[1]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[2]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[3]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[4]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[5]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[6]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[7]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[8]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[9]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[10]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[11]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[12]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[13]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[14]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[15]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[16]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[17]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[18]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[19]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[20]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[21]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[22]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[23]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[24]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[25]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[26]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[27]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[28]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[29]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[30]} {memctl/mem_ctl_top/crf/cr_rf[7]_14[31]}]]
set_property src_info {type:XDC file:2 line:931 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:932 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:933 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:934 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[6]_15[0]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[1]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[2]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[3]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[4]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[5]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[6]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[7]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[8]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[9]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[10]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[11]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[12]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[13]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[14]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[15]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[16]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[17]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[18]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[19]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[20]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[21]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[22]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[23]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[24]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[25]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[26]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[27]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[28]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[29]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[30]} {memctl/mem_ctl_top/crf/cr_rf[6]_15[31]}]]
set_property src_info {type:XDC file:2 line:935 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:936 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:937 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:938 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[5]_5[0]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[1]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[2]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[3]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[4]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[5]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[6]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[7]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[8]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[9]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[10]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[11]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[12]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[13]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[14]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[15]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[16]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[17]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[18]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[19]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[20]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[21]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[22]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[23]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[24]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[25]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[26]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[27]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[28]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[29]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[30]} {memctl/mem_ctl_top/crf/cr_rf[5]_5[31]}]]
set_property src_info {type:XDC file:2 line:939 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:940 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:941 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:942 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[4]_4[0]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[1]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[2]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[3]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[4]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[5]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[6]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[7]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[8]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[9]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[10]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[11]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[12]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[13]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[14]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[15]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[16]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[17]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[18]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[19]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[20]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[21]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[22]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[23]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[24]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[25]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[26]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[27]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[28]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[29]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[30]} {memctl/mem_ctl_top/crf/cr_rf[4]_4[31]}]]
set_property src_info {type:XDC file:2 line:943 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:944 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:945 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:946 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[3]_3[0]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[1]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[2]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[3]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[4]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[5]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[6]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[7]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[8]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[9]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[10]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[11]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[12]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[13]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[14]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[15]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[16]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[17]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[18]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[19]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[20]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[21]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[22]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[23]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[24]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[25]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[26]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[27]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[28]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[29]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[30]} {memctl/mem_ctl_top/crf/cr_rf[3]_3[31]}]]
set_property src_info {type:XDC file:2 line:947 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:948 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:949 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:950 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[2]_2[0]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[1]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[2]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[3]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[4]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[5]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[6]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[7]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[8]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[9]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[10]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[11]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[12]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[13]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[14]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[15]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[16]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[17]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[18]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[19]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[20]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[21]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[22]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[23]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[24]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[25]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[26]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[27]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[28]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[29]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[30]} {memctl/mem_ctl_top/crf/cr_rf[2]_2[31]}]]
set_property src_info {type:XDC file:2 line:951 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:952 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:953 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:954 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[15]_6[0]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[1]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[2]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[3]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[4]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[5]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[6]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[7]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[8]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[9]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[10]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[11]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[12]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[13]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[14]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[15]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[16]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[17]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[18]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[19]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[20]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[21]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[22]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[23]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[24]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[25]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[26]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[27]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[28]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[29]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[30]} {memctl/mem_ctl_top/crf/cr_rf[15]_6[31]}]]
set_property src_info {type:XDC file:2 line:955 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:956 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:957 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:958 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[14]_7[0]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[1]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[2]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[3]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[4]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[5]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[6]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[7]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[8]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[9]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[10]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[11]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[12]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[13]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[14]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[15]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[16]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[17]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[18]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[19]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[20]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[21]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[22]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[23]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[24]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[25]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[26]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[27]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[28]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[29]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[30]} {memctl/mem_ctl_top/crf/cr_rf[14]_7[31]}]]
set_property src_info {type:XDC file:2 line:959 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:960 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:961 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:962 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[1]_1[0]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[1]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[2]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[3]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[4]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[5]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[6]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[7]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[8]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[9]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[10]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[11]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[12]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[13]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[14]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[15]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[16]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[17]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[18]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[19]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[20]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[21]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[22]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[23]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[24]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[25]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[26]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[27]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[28]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[29]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[30]} {memctl/mem_ctl_top/crf/cr_rf[1]_1[31]}]]
set_property src_info {type:XDC file:2 line:963 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:964 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:965 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:966 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[13]_8[0]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[1]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[2]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[3]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[4]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[5]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[6]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[7]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[8]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[9]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[10]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[11]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[12]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[13]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[14]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[15]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[16]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[17]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[18]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[19]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[20]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[21]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[22]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[23]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[24]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[25]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[26]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[27]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[28]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[29]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[30]} {memctl/mem_ctl_top/crf/cr_rf[13]_8[31]}]]
set_property src_info {type:XDC file:2 line:967 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:968 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:969 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:970 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[12]_9[0]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[1]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[2]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[3]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[4]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[5]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[6]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[7]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[8]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[9]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[10]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[11]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[12]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[13]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[14]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[15]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[16]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[17]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[18]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[19]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[20]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[21]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[22]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[23]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[24]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[25]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[26]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[27]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[28]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[29]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[30]} {memctl/mem_ctl_top/crf/cr_rf[12]_9[31]}]]
set_property src_info {type:XDC file:2 line:971 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:972 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:973 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:974 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[11]_10[0]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[1]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[2]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[3]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[4]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[5]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[6]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[7]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[8]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[9]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[10]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[11]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[12]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[13]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[14]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[15]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[16]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[17]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[18]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[19]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[20]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[21]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[22]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[23]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[24]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[25]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[26]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[27]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[28]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[29]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[30]} {memctl/mem_ctl_top/crf/cr_rf[11]_10[31]}]]
set_property src_info {type:XDC file:2 line:975 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:976 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:977 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:978 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[10]_11[0]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[1]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[2]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[3]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[4]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[5]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[6]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[7]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[8]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[9]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[10]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[11]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[12]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[13]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[14]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[15]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[16]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[17]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[18]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[19]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[20]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[21]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[22]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[23]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[24]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[25]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[26]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[27]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[28]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[29]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[30]} {memctl/mem_ctl_top/crf/cr_rf[10]_11[31]}]]
set_property src_info {type:XDC file:2 line:979 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:980 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:981 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:982 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {memctl/mem_ctl_top/crf/cr_rf[0]_0[0]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[1]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[2]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[3]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[4]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[5]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[6]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[7]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[8]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[9]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[10]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[11]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[12]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[13]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[14]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[15]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[16]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[17]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[18]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[19]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[20]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[21]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[22]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[23]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[24]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[25]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[26]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[27]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[28]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[29]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[30]} {memctl/mem_ctl_top/crf/cr_rf[0]_0[31]}]]
set_property src_info {type:XDC file:2 line:983 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:984 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:985 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:986 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list memctl/imoControllerIO_imo_out_valid]]
set_property src_info {type:XDC file:2 line:987 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:988 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:989 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:990 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list memctl/imo_req_ack]]
set_property src_info {type:XDC file:2 line:991 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:992 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:993 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:994 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets ui_clk]
