# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rchip_axi4_xbar/rchip_axi4_xbar.xci
# IP: The module: 'rchip_axi4_xbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rchip_axi4_xbar/rchip_axi4_xbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rchip_axi4_xbar'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rchip_axi4_xbar/rchip_axi4_xbar.xci
# IP: The module: 'rchip_axi4_xbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ataberk/EasyDRAM/controller-hardware/ZC706/Vivado_Project/E2E_RowClone.srcs/sources_1/ip/rchip_axi4_xbar/rchip_axi4_xbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rchip_axi4_xbar'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
